# Generated by Django 4.2.8 on 2023-12-15 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 15, 18, 48, 26, 771257)),
        ),
    ]
